# Generated by Django 2.2.6 on 2019-10-26 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mess',
            fields=[
                ('mess_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('mess_name', models.CharField(max_length=30)),
                ('mess_capacity', models.IntegerField()),
                ('mess_type', models.CharField(max_length=50)),
                ('mess_boys', models.BooleanField()),
                ('mess_img', models.ImageField(upload_to='')),
                ('mess_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stu_reg_no', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('stu_name', models.CharField(max_length=50)),
                ('stu_gender', models.CharField(max_length=2)),
                ('stu_degree', models.CharField(max_length=50)),
                ('stu_dept', models.CharField(max_length=50)),
                ('stu_hostel_block', models.CharField(max_length=20)),
                ('stu_room_no', models.IntegerField()),
                ('stu_email', models.EmailField(max_length=50, unique=True)),
                ('stu_contact', models.IntegerField(unique=True)),
                ('stu_mess_roll_no', models.CharField(max_length=10, unique=True)),
                ('stu_img', models.ImageField(upload_to='images')),
                ('stu_sign', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='MessAllot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allot_mess', models.BooleanField(default=False)),
                ('allot_date', models.DateField()),
                ('allot_card_no', models.CharField(max_length=20)),
                ('allot_mess_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.Mess')),
                ('allot_reg_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.Student')),
            ],
        ),
        migrations.CreateModel(
            name='FeeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100)),
                ('fee_status', models.BooleanField(default=False)),
                ('stu_reg_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.Student')),
            ],
        ),
    ]
