# Generated by Django 2.2.6 on 2019-10-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stu_password',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
    ]
